{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "ad4ae2c8-3abc-4406-a4b9-275bbfd06a52",
   "metadata": {},
   "source": [
    "1-Explain why we have to use the Exception class while creating a Custom Exception."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "718113d3-9351-4f9a-9449-e1fd4f400237",
   "metadata": {},
   "source": [
    "Ans:\n",
    "    Using the Exception class as the base when creating a custom exception in Python is a recommended practice due to several important reasons:\n",
    "\n",
    "Inheritance and Hierarchy: The Exception class is at the top of the exception hierarchy in Python. By subclassing it, you create a well-structured hierarchy for your custom exceptions. This makes it easier to manage and handle different types of exceptions with varying behaviors.\n",
    "\n",
    "Consistency: Python's exception handling system is designed around inheritance. By basing your custom exception on the Exception class, you ensure that your custom exception behaves consistently with other built-in exceptions. This consistency helps other developers understand and work with your custom exceptions more effectively.\n",
    "\n",
    "Exception Handling: When you use the Exception class as the base, your custom exception can be caught using a broader except block that catches generic exceptions. This allows for more flexible and organized error handling, as you can group and handle custom exceptions together with built-in exceptions in a single except block.\n",
    "\n",
    "Compatibility: Since Python's exception system relies on inheritance, basing your custom exception on the Exception class ensures compatibility with existing exception-handling code, libraries, and frameworks. It aligns your custom exception with the established conventions of the Python programming language.\n",
    "\n",
    "Customization: While you inherit essential behavior from the Exception class, you can still customize your custom exception with additional attributes, methods, and specific behavior that suits your application's requirements.\n",
    "\n",
    "Here's an illustrative example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "71e09985-1aa7-4eaf-a767-4c8cc94db871",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Custom Exception: This is a custom exception\n"
     ]
    }
   ],
   "source": [
    "class CustomException(Exception):\n",
    "    def __init__(self, message):\n",
    "        self.message = message\n",
    "        super().__init__(self.message)\n",
    "\n",
    "try:\n",
    "    raise CustomException(\"This is a custom exception\")\n",
    "except CustomException as ce:\n",
    "    print(f\"Custom Exception: {ce}\")\n",
    "except Exception as e:\n",
    "    print(f\"Generic Exception: {e}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f4819118-359e-4653-be6d-e444f1c76f69",
   "metadata": {},
   "source": [
    "2- Write a python program to print Python Exception Hierarchy."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "4632eca4-d58f-4279-b037-1040ec9312c7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception\n",
      "  TypeError\n",
      "    FloatOperation\n",
      "    MultipartConversionError\n",
      "  StopAsyncIteration\n",
      "  StopIteration\n",
      "  ImportError\n",
      "    ModuleNotFoundError\n",
      "    ZipImportError\n",
      "  OSError\n",
      "    ConnectionError\n",
      "      BrokenPipeError\n",
      "      ConnectionAbortedError\n",
      "      ConnectionRefusedError\n",
      "      ConnectionResetError\n",
      "        RemoteDisconnected\n",
      "    BlockingIOError\n",
      "    ChildProcessError\n",
      "    FileExistsError\n",
      "    FileNotFoundError\n",
      "    IsADirectoryError\n",
      "    NotADirectoryError\n",
      "    InterruptedError\n",
      "      InterruptedSystemCall\n",
      "    PermissionError\n",
      "    ProcessLookupError\n",
      "    TimeoutError\n",
      "    UnsupportedOperation\n",
      "    itimer_error\n",
      "    herror\n",
      "    gaierror\n",
      "    SSLError\n",
      "      SSLCertVerificationError\n",
      "      SSLZeroReturnError\n",
      "      SSLWantWriteError\n",
      "      SSLWantReadError\n",
      "      SSLSyscallError\n",
      "      SSLEOFError\n",
      "    Error\n",
      "      SameFileError\n",
      "    SpecialFileError\n",
      "    ExecError\n",
      "    ReadError\n",
      "    URLError\n",
      "      HTTPError\n",
      "      ContentTooShortError\n",
      "    BadGzipFile\n",
      "  EOFError\n",
      "    IncompleteReadError\n",
      "  RuntimeError\n",
      "    RecursionError\n",
      "    NotImplementedError\n",
      "      ZMQVersionError\n",
      "      StdinNotImplementedError\n",
      "    _DeadlockError\n",
      "    BrokenBarrierError\n",
      "    BrokenExecutor\n",
      "      BrokenThreadPool\n",
      "    SendfileNotAvailableError\n",
      "    ExtractionError\n",
      "    VariableError\n",
      "  NameError\n",
      "    UnboundLocalError\n",
      "  AttributeError\n",
      "    FrozenInstanceError\n",
      "  SyntaxError\n",
      "    IndentationError\n",
      "      TabError\n",
      "  LookupError\n",
      "    IndexError\n",
      "    KeyError\n",
      "      NoSuchKernel\n",
      "      UnknownBackend\n",
      "    CodecRegistryError\n",
      "  ValueError\n",
      "    UnicodeError\n",
      "      UnicodeEncodeError\n",
      "      UnicodeDecodeError\n",
      "      UnicodeTranslateError\n",
      "    UnsupportedOperation\n",
      "    JSONDecodeError\n",
      "    SSLCertVerificationError\n",
      "    Error\n",
      "    UnsupportedDigestmodError\n",
      "    IllegalMonthError\n",
      "    IllegalWeekdayError\n",
      "    ParserError\n",
      "    ClassNotFound\n",
      "    ClipboardEmpty\n",
      "    MessageDefect\n",
      "      NoBoundaryInMultipartDefect\n",
      "      StartBoundaryNotFoundDefect\n",
      "      CloseBoundaryNotFoundDefect\n",
      "      FirstHeaderLineIsContinuationDefect\n",
      "      MisplacedEnvelopeHeaderDefect\n",
      "      MissingHeaderBodySeparatorDefect\n",
      "      MultipartInvariantViolationDefect\n",
      "      InvalidMultipartContentTransferEncodingDefect\n",
      "      UndecodableBytesDefect\n",
      "      InvalidBase64PaddingDefect\n",
      "      InvalidBase64CharactersDefect\n",
      "      InvalidBase64LengthDefect\n",
      "      HeaderDefect\n",
      "        InvalidHeaderDefect\n",
      "        HeaderMissingRequiredValue\n",
      "        NonPrintableDefect\n",
      "        ObsoleteHeaderDefect\n",
      "        NonASCIILocalPartDefect\n",
      "        InvalidDateDefect\n",
      "    MacroToEdit\n",
      "    InvalidFileException\n",
      "    UnequalIterablesError\n",
      "    InvalidVersion\n",
      "    _InvalidELFFileHeader\n",
      "    InvalidWheelFilename\n",
      "    InvalidSdistFilename\n",
      "    InvalidSpecifier\n",
      "    InvalidMarker\n",
      "    UndefinedComparison\n",
      "    UndefinedEnvironmentName\n",
      "    InvalidRequirement\n",
      "      RequirementParseError\n",
      "    InvalidVersion\n",
      "  AssertionError\n",
      "  ArithmeticError\n",
      "    FloatingPointError\n",
      "    OverflowError\n",
      "    ZeroDivisionError\n",
      "      DivisionByZero\n",
      "      DivisionUndefined\n",
      "    DecimalException\n",
      "      Clamped\n",
      "      Rounded\n",
      "        Underflow\n",
      "        Overflow\n",
      "      Inexact\n",
      "        Underflow\n",
      "        Overflow\n",
      "      Subnormal\n",
      "        Underflow\n",
      "      DivisionByZero\n",
      "      FloatOperation\n",
      "      InvalidOperation\n",
      "        ConversionSyntax\n",
      "        DivisionImpossible\n",
      "        DivisionUndefined\n",
      "        InvalidContext\n",
      "  SystemError\n",
      "    CodecRegistryError\n",
      "  ReferenceError\n",
      "  MemoryError\n",
      "  BufferError\n",
      "  Warning\n",
      "    UserWarning\n",
      "      GetPassWarning\n",
      "      FormatterWarning\n",
      "    EncodingWarning\n",
      "    DeprecationWarning\n",
      "      ProvisionalWarning\n",
      "    PendingDeprecationWarning\n",
      "    SyntaxWarning\n",
      "    RuntimeWarning\n",
      "      ProactorSelectorThreadWarning\n",
      "      UnknownTimezoneWarning\n",
      "      PEP440Warning\n",
      "    FutureWarning\n",
      "      ProvisionalCompleterWarning\n",
      "    ImportWarning\n",
      "    UnicodeWarning\n",
      "    BytesWarning\n",
      "    ResourceWarning\n",
      "    DeprecatedTzFormatWarning\n",
      "    PkgResourcesDeprecationWarning\n",
      "  _OptionError\n",
      "  _Error\n",
      "  error\n",
      "  Verbose\n",
      "  Error\n",
      "  SubprocessError\n",
      "    CalledProcessError\n",
      "    TimeoutExpired\n",
      "  TokenError\n",
      "  StopTokenizing\n",
      "  ClassFoundException\n",
      "  EndOfBlock\n",
      "  TraitError\n",
      "  Error\n",
      "  Error\n",
      "    CancelledError\n",
      "    TimeoutError\n",
      "    InvalidStateError\n",
      "  _GiveupOnSendfile\n",
      "  error\n",
      "  Incomplete\n",
      "  TimeoutError\n",
      "  InvalidStateError\n",
      "  LimitOverrunError\n",
      "  QueueEmpty\n",
      "  QueueFull\n",
      "  Empty\n",
      "  Full\n",
      "  ArgumentError\n",
      "  ZMQBaseError\n",
      "    ZMQError\n",
      "      ContextTerminated\n",
      "      Again\n",
      "      InterruptedSystemCall\n",
      "    ZMQBindError\n",
      "    NotDone\n",
      "  PickleError\n",
      "    PicklingError\n",
      "    UnpicklingError\n",
      "  _Stop\n",
      "  ArgumentError\n",
      "  ArgumentTypeError\n",
      "  ConfigError\n",
      "    ConfigLoaderError\n",
      "      ArgumentError\n",
      "    ConfigFileNotFound\n",
      "  ConfigurableError\n",
      "    MultipleInstanceError\n",
      "  ApplicationError\n",
      "  error\n",
      "  TimeoutError\n",
      "  error\n",
      "  ReturnValueIgnoredError\n",
      "  KeyReuseError\n",
      "  UnknownKeyError\n",
      "  LeakedCallbackError\n",
      "  BadYieldError\n",
      "  ReturnValueIgnoredError\n",
      "  Return\n",
      "  InvalidPortNumber\n",
      "  error\n",
      "  LZMAError\n",
      "  RegistryError\n",
      "  _GiveupOnFastCopy\n",
      "  Error\n",
      "    NoSectionError\n",
      "    DuplicateSectionError\n",
      "    DuplicateOptionError\n",
      "    NoOptionError\n",
      "    InterpolationError\n",
      "      InterpolationMissingOptionError\n",
      "      InterpolationSyntaxError\n",
      "      InterpolationDepthError\n",
      "    ParsingError\n",
      "      MissingSectionHeaderError\n",
      "  NoIPAddresses\n",
      "  BadZipFile\n",
      "  LargeZipFile\n",
      "  BadEntryPoint\n",
      "  NoSuchEntryPoint\n",
      "  DuplicateKernelError\n",
      "  ErrorDuringImport\n",
      "  NotOneValueFound\n",
      "  CannotEval\n",
      "  OptionError\n",
      "  BdbQuit\n",
      "  Restart\n",
      "  ExceptionPexpect\n",
      "    EOF\n",
      "    TIMEOUT\n",
      "  PtyProcessError\n",
      "  FindCmdError\n",
      "  HomeDirError\n",
      "  ProfileDirError\n",
      "  IPythonCoreError\n",
      "    TryNext\n",
      "    UsageError\n",
      "    StdinNotImplementedError\n",
      "  InputRejected\n",
      "  GetoptError\n",
      "  ErrorToken\n",
      "  PrefilterError\n",
      "  AliasError\n",
      "    InvalidAliasError\n",
      "  Error\n",
      "    InterfaceError\n",
      "    DatabaseError\n",
      "      InternalError\n",
      "      OperationalError\n",
      "      ProgrammingError\n",
      "      IntegrityError\n",
      "      DataError\n",
      "      NotSupportedError\n",
      "  Warning\n",
      "  SpaceInInput\n",
      "  DOMException\n",
      "    IndexSizeErr\n",
      "    DomstringSizeErr\n",
      "    HierarchyRequestErr\n",
      "    WrongDocumentErr\n",
      "    InvalidCharacterErr\n",
      "    NoDataAllowedErr\n",
      "    NoModificationAllowedErr\n",
      "    NotFoundErr\n",
      "    NotSupportedErr\n",
      "    InuseAttributeErr\n",
      "    InvalidStateErr\n",
      "    SyntaxErr\n",
      "    InvalidModificationErr\n",
      "    NamespaceErr\n",
      "    InvalidAccessErr\n",
      "    ValidationErr\n",
      "  ValidationError\n",
      "  EditReadOnlyBuffer\n",
      "  _Retry\n",
      "  InvalidLayoutError\n",
      "  HeightIsUnknownError\n",
      "  ParserSyntaxError\n",
      "  InternalParseError\n",
      "  _PositionUpdatingFinished\n",
      "  SimpleGetItemNotFound\n",
      "  UncaughtAttributeError\n",
      "  HasNoContext\n",
      "  ParamIssue\n",
      "  _JediError\n",
      "    InternalError\n",
      "    WrongVersion\n",
      "    RefactoringError\n",
      "  OnErrorLeaf\n",
      "  InvalidPythonEnvironment\n",
      "  MessageError\n",
      "    MessageParseError\n",
      "      HeaderParseError\n",
      "      BoundaryError\n",
      "    MultipartConversionError\n",
      "    CharsetError\n",
      "  Error\n",
      "  HTTPException\n",
      "    NotConnected\n",
      "    InvalidURL\n",
      "    UnknownProtocol\n",
      "    UnknownTransferEncoding\n",
      "    UnimplementedFileMode\n",
      "    IncompleteRead\n",
      "    ImproperConnectionState\n",
      "      CannotSendRequest\n",
      "      CannotSendHeader\n",
      "      ResponseNotReady\n",
      "    BadStatusLine\n",
      "      RemoteDisconnected\n",
      "    LineTooLong\n",
      "  InteractivelyDefined\n",
      "  KillEmbedded\n",
      "  Error\n",
      "    NoSuchProcess\n",
      "      ZombieProcess\n",
      "    AccessDenied\n",
      "    TimeoutExpired\n",
      "  _Ipv6UnsupportedError\n",
      "  QueueEmpty\n",
      "  QueueFull\n",
      "  DebuggerInitializationError\n",
      "  ExpatError\n",
      "  Error\n",
      "    ProtocolError\n",
      "    ResponseError\n",
      "    Fault\n",
      "  ParseBaseException\n",
      "    ParseException\n",
      "    ParseFatalException\n",
      "      ParseSyntaxException\n",
      "  RecursiveGrammarException\n",
      "  ResolutionError\n",
      "    VersionConflict\n",
      "      ContextualVersionConflict\n",
      "    DistributionNotFound\n",
      "    UnknownExtra\n",
      "  _Error\n",
      "  UnableToResolveVariableException\n",
      "  InvalidTypeInArgsException\n",
      "  CustomException\n"
     ]
    }
   ],
   "source": [
    "def print_exception_hierarchy(exception_class, depth=0):\n",
    "    indent = \"  \" * depth\n",
    "    print(f\"{indent}{exception_class.__name__}\")\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, depth + 1)\n",
    "\n",
    "print_exception_hierarchy(Exception)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d90a4e0e-2338-4ff0-8a81-bb2057e0ea83",
   "metadata": {},
   "source": [
    "3-What errors are defined in the ArithmeticError class? Explain any two with an example.?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "663239bb-defb-4610-a348-6e42f3988e5a",
   "metadata": {},
   "source": [
    "Ans:\n",
    "    The ArithmeticError class is a base class for exceptions that occur during arithmetic operations. It serves as a parent class for a number of more specific arithmetic-related exceptions. Two common exceptions that are derived from ArithmeticError are ZeroDivisionError and OverflowError. Let's explore these two exceptions with examples:\n",
    "\n",
    "ZeroDivisionError:\n",
    "This exception is raised when attempting to divide a number by zero.\n",
    "It indicates that the division operation is not possible due to the divisor being zero."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "861dd44f-2446-42fe-93ec-cb12fe767b6e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: division by zero\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    result = 10 / 0\n",
    "except ZeroDivisionError as zde:\n",
    "    print(f\"Error: {zde}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7f688dcb-f4a5-46fa-bc0e-db8aab75ab24",
   "metadata": {},
   "source": [
    "OverflowError:\n",
    "This exception is raised when an arithmetic operation exceeds the limits of the data type being used, resulting in a number that is too large to be represented.\n",
    "This typically occurs with integer operations that produce values beyond the range that can be stored."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "8fa4fb0a-1b74-4ed2-815b-8087e0246b81",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "\n",
    "try:\n",
    "    large_number = sys.maxsize\n",
    "    result = large_number + 1\n",
    "except OverflowError as oe:\n",
    "    print(f\"Error: {oe}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b16db834-15da-46f4-9c75-7a240e958383",
   "metadata": {},
   "source": [
    "4-Why LookupError class is used? Explain with an example KeyError and IndexError.?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "30473aa9-e080-4183-8da7-f5290afd689f",
   "metadata": {},
   "source": [
    "Ans:\n",
    "    The LookupError class is a base class for exceptions that occur when a specified key or index is not found. It serves as a parent class for exceptions related to lookup operations, such as dictionary keys, list indices, and more. Two common exceptions that are derived from LookupError are KeyError and IndexError. Let's explore these two exceptions with examples:\n",
    "\n",
    "KeyError:\n",
    "This exception is raised when a dictionary is accessed using a key that doesn't exist in the dictionary.\n",
    "It indicates that the specified key is not present in the dictionary."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "a0791cfc-9d3c-401c-8168-33262e0ead16",
   "metadata": {},
   "outputs": [],
   "source": [
    "import logging\n",
    "logging.basicConfig(filename = 'test-1' , level=logging.ERROR)\n",
    "try:\n",
    "    a={'key1':\"yash\" , 'key2':\"Kush\"}\n",
    "    print(a['key3'])\n",
    "except KeyError as e:\n",
    "    logging.error(\"I am trying to resolve key eroor {}\".format(e))\n",
    "    "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3bd064ed-d5db-4850-8626-5832d349d111",
   "metadata": {},
   "source": [
    "IndexError:\n",
    "This exception is raised when trying to access an index that is out of range of a sequence (e.g., list, tuple, string).\n",
    "It indicates that the specified index is not valid for the given sequence."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "d7515ed5-cf89-4cf2-821c-9332933f0e16",
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "    l=[1,2,3,4]\n",
    "    print(l[4])\n",
    "except IndexError as e:\n",
    "    logging.error(\"I am trying to resolve index eroor {}\".format(e))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ef35ab3b-bdc5-445e-bf59-33a18d7bb74b",
   "metadata": {},
   "source": [
    "5-Explain ImportError. What is ModuleNotFoundError?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e3fdf2f7-2e77-4246-9854-52af67d13a9d",
   "metadata": {},
   "source": [
    "Ans:\n",
    "    ImportError and ModuleNotFoundError are both exceptions in Python that are related to importing modules. Let's explore each of them:\n",
    "\n",
    "ImportError:\n",
    "ImportError is raised when an imported module, package, or attribute cannot be found or loaded. This can occur for various reasons, such as a typo in the module name, an issue with the module's content, or problems with the module's dependencies.\n",
    "It is a generic exception that covers a range of import-related errors.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "cbce3433-209f-492f-ab63-00e4afb3f9c7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Import Error: No module named 'non_existent_module'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import non_existent_module\n",
    "except ImportError as ie:\n",
    "    print(f\"Import Error: {ie}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "40ad66e4-b51d-41dc-82d6-f3af4c461318",
   "metadata": {},
   "source": [
    "ModuleNotFoundError:\n",
    "ModuleNotFoundError is a subclass of ImportError introduced in Python 3.6. It specifically indicates that the module being imported cannot be found.\n",
    "It provides a clearer error message than the generic ImportError and includes the module name that could not be located."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "471231d9-5ff4-4074-9a9b-a9173179bad0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Module Not Found Error: No module named 'non_existent_module'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import non_existent_module\n",
    "except ModuleNotFoundError as mne:\n",
    "    print(f\"Module Not Found Error: {mne}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "dfc84bf6-82d2-4be9-9c51-6fce94b99236",
   "metadata": {},
   "source": [
    "6-List down some best practices for exception handling in python."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4550cccf-6f4d-4bf8-ae4e-0089362f0793",
   "metadata": {},
   "source": [
    "Ans:\n",
    "    Be Specific in Exception Types: Use specific exception types when catching exceptions. This helps you handle different error scenarios with appropriate strategies.\n",
    "\n",
    "Use Multiple except Blocks: Use separate except blocks for different exception types. This makes your code more readable and allows you to handle errors more accurately.\n",
    "\n",
    "Use try-except Blocks Sparingly: Don't overuse try-except blocks. Place them only around the code that might raise exceptions, rather than wrapping entire blocks of code.\n",
    "\n",
    "Use else to Separate Normal Flow: Use the else block after try to execute code that should run only when no exceptions occur. This keeps your error-handling logic separate from regular code.\n",
    "\n",
    "Use finally for Cleanup: Use the finally block to ensure that cleanup operations (like closing files or releasing resources) are always performed, regardless of exceptions.\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9baf3453-0835-40eb-8240-29a3e103909b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
